spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    root: info
    com.example.ll.finalproject.app: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  site:
    name: FinalProject
    baseUrl: "http://localhost:8010"
  jwt:
    secretKey: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
