spring:
  profiles:
    active: dev
    include: apikey
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: ALWAYS
  #        스프링 배치 관련 DB 자동생성
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: aaddss528528@gmail.com
    password: ${GOOGLE_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: info
    com.example.ll.finalproject.app: debug
    org.hibernate.type.descriptor.sql: trace
custom:
  site:
    name: FinalProject
    baseUrl: "http://localhost:8010"
